spring:
  application:
    name: concurrency-lab
  datasource:
    url: jdbc:mysql://localhost:3306/concurrency_lab
    username: root
    password: 5404
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          isolation: 2
